# Generated by Django 4.1.2 on 2022-12-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="dataikan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jenis_usaha", models.CharField(max_length=50)),
                ("provinsi", models.CharField(max_length=50)),
                ("jenis_ikan", models.CharField(max_length=50)),
                ("tahun", models.CharField(max_length=10)),
                ("vol_produksi", models.CharField(max_length=100)),
                ("nilai_produksi", models.CharField(max_length=100)),
            ],
        ),
    ]
