# Generated by Django 4.1.2 on 2022-12-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MSY", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="dataikan", name="nilai_produksi",),
        migrations.RemoveField(model_name="dataikan", name="vol_produksi",),
        migrations.AddField(
            model_name="dataikan",
            name="ton",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="dataikan",
            name="trip",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
