# Generated by Django 4.1.2 on 2022-12-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MSY", "0002_remove_dataikan_nilai_produksi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataikan", name="tahun", field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="dataikan", name="ton", field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="dataikan", name="trip", field=models.FloatField(null=True),
        ),
    ]
