# Generated by Django 4.1.2 on 2022-12-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MSY", "0003_alter_dataikan_tahun_alter_dataikan_ton_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataikan", name="tahun", field=models.DateTimeField(null=True),
        ),
    ]
