# Generated by Django 4.1.2 on 2022-12-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MSY", "0008_alter_dataikan_ton"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataikan", name="ton", field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="dataikan", name="trip", field=models.FloatField(null=True),
        ),
    ]
