# Generated by Django 4.1.2 on 2022-12-23 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MSY", "0011_uploadedfile2"),
    ]

    operations = [
        migrations.DeleteModel(name="UploadedFile2",),
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(
                upload_to="static/legenda/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["zip", "rar"]
                    )
                ],
            ),
        ),
    ]
