# Generated by Django 4.1.2 on 2022-12-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userview", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoJSON",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("data", models.TextField()),
            ],
        ),
    ]
