# Generated by Django 4.1.2 on 2022-12-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userview", "0002_geojson"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="files/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(name="GeoJSON",),
    ]
