# Generated by Django 4.1.2 on 2022-12-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userview", "0003_uploadedfile_delete_geojson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(upload_to="static/legenda/"),
        ),
    ]
