# Generated by Django 4.1.2 on 2022-12-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userview", "0004_alter_uploadedfile_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
