# Generated by Django 4.1.2 on 2022-12-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userview", "0006_remove_uploadedfile_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
