# Generated by Django 4.1.2 on 2022-12-23 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userview", "0008_alter_uploadedfile_file"),
    ]

    operations = [
        migrations.DeleteModel(name="UploadedFile",),
    ]
